dev = false

[general]
discord-invite = "fJBXvq28bx"
rules = [
    ["No spamming.", ["This is self explanatory.\n\nNo repetitive or large volume messaging."]],
    ["No disrespect.", ["<inclusion>:\n- Harassment.\n- Uncomfortable or triggering comments.\n- Misgendering."]],
    ["No inappropriacy.", ["<inclusion>\n- NSFW discussion.\n- Jokes about terrorism or other triggering topics.\n- Heated political discussions."]],
    ["No illegal activities.", ["<inclusion>\n- Drugs or bomb/weapon making.\n- Threatening/wishing harm upon members.\n- Threatening to or releasing personal info about members.\n- Predatory behavior."]],
    ["No offensive behavior.", ["<inclusion>\n- Using slurs or partaking in hate speech.\n- Discrimination towards certain groups or minorities."]],
    ["No behavior harmful to the server or other members.", [
        "<inclusion>\n- Abusing bugs or unintended behavior.\n- Lagging the server.\n- Advertising other servers.",
        "- Advertising other servers.\n- Using modifications to gain a competitive edge over others.\n- Spawn killing members.\n- Repetitively sending a player to solitary.\n- Using alts.\n- Using macros.",
        "- Assisting authorities (\"mini-knighting\")."]]
]

[warden.prefix]
banned-containers = [
    "SOLITARY",
    "BOOSTER",
    "ASCENDING"
]

[warden.help]
help = { args = [""], description = "Shows you this menu." }
solitary = { args = ["name"], description = "Sends a player to solitary, later to torture them. <red>[PLAYER MUST BE DEAD]" }
target = { args = ["name"], description = "Turns a player in a target." }
prefix = { args = ["prefix"], description = "Adds a prefix to your name." }
femboys = { args = [""], description = "Toggles femboy mode for nurses." }
fire = { args = ["guard name"], description = "Fires a guard from their job" }
resign = { args = [""], description = "Resigns you from your job." }
release = { args = ["name"], description = "Releases a player from solitary." }
pass = { args = ["name"], description = "Gives a player warden." }
guard = { args = ["name"], description = "Makes another player a guard." }
swat = { args = ["name"], description = "Makes another player a SWAT guard. <red>[REQUIRES 'SWAT GUARDS' UPGRADE!]" }
nurse = { args = ["name"], description = "Makes another player a nurse." }
intercom = { args = ["msg"], description = "Plays a loud message to all players." }
grammar = { args = [""], description = "Makes all guards type with proper grammar." }
mutechat = { args = [""], description = "Forces all players to use team chat." }
skip = { args = [""], description = "Skips roll call." }

[discord]
token = ""
guild = ""
chat-channel = ""
commands-channel = ""
filter-channel = ""
linked-role = ""
muted-role = ""